- name: Create interface template per device-type
  netbox_device_interface_template:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      device_type: "{{ item['slug'] }}"
      name: "{{ interface['name'] }}"
      type: "{{ interface['type'] }}"
      mgmt_only: "{{ interface['mgmt_only'] if defined | default(false) else omit }}"
  with_items: "{{ item['interfaces'] }}"
  # when: item['interfaces'] is defined
  loop_control:
    loop_var: interface
    label: "{{ item['model'] }}\t{{ interface['name'] }}"