---
  - name: "Parsing the yaml files in another folder practice"
    hosts: localhost
    gather_facts: false
    connection: local
    collections:
      - netbox.netbox
    tasks:

    # - name: "Gather list of files in Cisco folder"
    #   find:
    #     paths:
    #       - "../devicetype-library/device-types/Cisco/"
    #   register: template_files
    
    # - name: "Refactor template_files"
    #   set_fact: template_files="{{ template_files.files | map(attribute='path') | list }}"

    # - name: "Second Refactor of template_files names"
    #   set_fact:
    #     template_files: "{{ item.split('/')[-1].split('.')[0] }}"
    #   with_items:
    #     - "{{ template_files }}"

    # - name: "Debug template_files"
    #   debug: var=template_files

    - name: "Pull variables from a static yml file in another dir"
      include_vars:
        file: ../devicetype-library/device-types/Cisco/asr1002-hx.yaml
        name: asr1002_hx

    - name: "Debugging variables pulled from the yml file"
      debug: 
        var: asr1002_hx

    - name: "Add manufacturer to Netbox"
      netbox_manufacturer:
        netbox_url: http://localhost:8000
        netbox_token: "{{ lookup('env', 'nb_token') }}"
        data:
          name: "{{ asr1002_hx.manufacturer }}"
  
    - name: "Build device template in Netbox"
      netbox_device_type:
        netbox_url: http://localhost:8000
        netbox_token: "{{ lookup('env', 'nb_token') }}"
        data:
          manufacturer: "{{ asr1002_hx.manufacturer }}"
          model: "{{ asr1002_hx.model }}"
          slug: "{{ asr1002_hx.slug }}"
          u_height: "{{ asr1002_hx.u_height }}"
          is_full_depth: "{{ asr1002_hx.is_full_depth }}"
        state: present