---
  - name: "Parsing the yaml files in another folder practice"
    hosts: localhost
    gather_facts: false
    connection: local
    collections:
      - netbox.netbox

    tasks:

    - name: "Gather list of files in Cisco folder"
      find:
        paths:
          - "../devicetype-library/device-types/Cisco/"
      register: template_files
    
    - name: "Gather filenames from template_files folder"
      set_fact: template_files="{{ template_files.files | map(attribute='path') | list }}"

    - name: "Get device_type vars from yaml files"
      include_vars:
        file: "{{ item }}"
        name: "{{ item | regex_replace('.*/(.*).(?:yaml)$', '\\1')}}"
      with_items: "{{ template_files }}"
      register: templates

    - name: "Cleanup templates tree"
      set_fact:
        templates: "{{ templates.results | map(attribute='ansible_facts') | list }}"
  
    - name: "Create set of manufacturers"
      set_fact: manufacturers="{{ item.values() | map(attribute='manufacturer') | list }}"
      with_items: "{{ templates }}"

    - name: "Add manufacturer to Netbox"
      netbox_manufacturer:
        netbox_url: http://localhost:8000
        netbox_token: "{{ lookup('env', 'nb_token') }}"
        data:
          name: "{{ item }}"
      with_items: "{{ manufacturers }}"

    - name: "Build device template in Netbox"
      netbox_device_type:
        netbox_url: http://localhost:8000
        netbox_token: "{{ lookup('env', 'nb_token') }}"
        data:
          manufacturer: "{{ item.values()[0]['manufacturer'] }}"
          model: "{{ item.values()[0]['model'] }}"
          slug: "{{ item.values()[0]['slug'] }}"
          u_height: "{{ item.values()[0]['u_height'] if defined | default(false) else omit  }}"
          is_full_depth: "{{ item.values()[0]['is_full_depth'] if defined | default(false) else omit }}"
        state: present
      with_items: "{{ templates }}"

    - name: "**** PLACEHOLDER FOR NEXT STEPS ****"
      debug: msg="Add task to add interface templates to device type profiles"